name = "dvwa-lab"
main = "src/index.ts"
compatibility_date = "2026-02-20"

# 1. Define the Container and point it to the Docker Hub image
[[containers]]
class_name = "DvwaContainer"
image = "registry.cloudflare.com/6db4bbca7eed4de5fb6c2382e1cd9ef1/custom-dvwa:v4"

# 2. Add your custom domain here
routes = [
  { pattern = "dvwa.tharunraj.co.in", custom_domain = true }
]

# 3. Bind the Container to a Durable Object so the Worker can talk to it
[[durable_objects.bindings]]
name = "DVWA_CONTAINER"
class_name = "DvwaContainer"

# 4. Apply the initial migration required for Durable Objects
[[migrations]]
tag = "v1"
new_sqlite_classes = ["DvwaContainer"]